apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-media
  namespace: gearlink
  labels:
    app: worker-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-media
  template:
    metadata:
      labels:
        app: worker-media
    spec:
      containers:
      - name: worker-media
        image: ghcr.io/kadir/gearlink/worker-media:latest
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
